{application,supercollider,
             [{applications,[kernel,stdlib,elixir,logger,osc]},
              {description,"An Elixir library for interacting with SuperCollider, an audio synthesis and composition platform."},
              {modules,['Elixir.SuperCollider',
                        'Elixir.SuperCollider.SoundServer',
                        'Elixir.SuperCollider.SoundServer.Command',
                        'Elixir.SuperCollider.SoundServer.Response',
                        'Elixir.SuperCollider.SynthDef',
                        'Elixir.SuperCollider.SynthDef.Encoder',
                        'Elixir.SuperCollider.SynthDef.Parser',
                        'Elixir.SuperCollider.SynthDef.ScFile',
                        'Elixir.SuperCollider.SynthDef.UGen']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
