{application,osc,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"OSC encoder/decoder for elixir"},
              {modules,['Elixir.OSC','Elixir.OSC.Bundle','Elixir.OSC.Decoder',
                        'Elixir.OSC.Decoder.Any','Elixir.OSC.EncodeError',
                        'Elixir.OSC.Encoder','Elixir.OSC.Encoder.Atom',
                        'Elixir.OSC.Encoder.BitString',
                        'Elixir.OSC.Encoder.Float',
                        'Elixir.OSC.Encoder.Integer',
                        'Elixir.OSC.Encoder.List',
                        'Elixir.OSC.Encoder.OSC.Bundle',
                        'Elixir.OSC.Encoder.OSC.Message',
                        'Elixir.OSC.Encoder.OSC.Packet',
                        'Elixir.OSC.Encoder.OSC.TimeTag','Elixir.OSC.Message',
                        'Elixir.OSC.Packet','Elixir.OSC.Parser',
                        'Elixir.OSC.TimeTag']},
              {registered,[]},
              {vsn,"0.1.2"}]}.
